import {PropsWithChildren, useState} from "react";
import type {Metadata} from "next";
import Logo from '@/app/assets/logo.png'
import Image from "next/image";
import '@/app/styles/scss/layouts/default.scss';
import LayoutHeader from "@/components/layouts/Header";

export const metadata: Metadata = {
    title: "Landing",
    description: "Generated by create next app",
};

const DefaultLayout = ({children}: PropsWithChildren) => {
    return <div className='wrap-default-layout'>
        <LayoutHeader/>
        <main>
            {children}
        </main>
    </div>
}

export default DefaultLayout